#cloud-config

package_update: true
package_upgrade: true

write_files:
  - encoding: b64
    content: W1NlYXREZWZhdWx0c10KZ3JlZXRlci1zZXNzaW9uPXVuaXR5LWdyZWV0ZXIKdXNlci1zZXNzaW9uPXhmY2U=
    owner: root:root
    path: /usr/share/lightdm/lightdm.conf.d/50-xfce-greeter.conf
    permissions: "0755"
  - encoding: b64
    content: W1NlcnZlcl0KcGF0aCA9IC91c3IvYmluL2duczNzZXJ2ZXIKdWJyaWRnZV9wYXRoID0gL3Vzci9iaW4vdWJyaWRnZQpob3N0ID0gbG9jYWxob3N0CnBvcnQgPSAzMDgwCmltYWdlc19wYXRoID0gL2hvbWUvdWJ1bnR1L0dOUzMvaW1hZ2VzCnByb2plY3RzX3BhdGggPSAvaG9tZS91YnVudHUvR05TMy9wcm9qZWN0cwphcHBsaWFuY2VzX3BhdGggPSAvaG9tZS91YnVudHUvR05TMy9hcHBsaWFuY2VzCmFkZGl0aW9uYWxfaW1hZ2VzX3BhdGhzID0gCnN5bWJvbHNfcGF0aCA9IC9ob21lL3VidW50dS9HTlMzL3N5bWJvbHMKY29uZmlnc19wYXRoID0gL2hvbWUvdWJ1bnR1L0dOUzMvY29uZmlncwpyZXBvcnRfZXJyb3JzID0gVHJ1ZQphdXRvX3N0YXJ0ID0gVHJ1ZQphbGxvd19jb25zb2xlX2Zyb21fYW55d2hlcmUgPSBGYWxzZQphdXRoID0gVHJ1ZQp1c2VyID0gYWRtaW4KcGFzc3dvcmQgPSBnanVaV29PRlpLTFo1RXdRU0NCZ2drWGZqR0R2anVMNGE0N0ZFR20yV3RjNEhua21FWk4xMUlnYUJqeFZTUTVmCnByb3RvY29sID0gaHR0cApjb25zb2xlX3N0YXJ0X3BvcnRfcmFuZ2UgPSA1MDAwCmNvbnNvbGVfZW5kX3BvcnRfcmFuZ2UgPSAxMDAwMAp1ZHBfc3RhcnRfcG9ydF9yYW5nZSA9IDEwMDAwCnVkcF9lbmRfcG9ydF9yYW5nZSA9IDIwMDAw
    owner: root:root
    path: /home/ubuntu/.config/GNS3/2.2/gns3_server.conf
    permissions: "0664"
  - encoding: b64
    content: ewogICAgIkJ1aWx0aW4iOiB7CiAgICAgICAgImRlZmF1bHRfbmF0X2ludGVyZmFjZSI6ICJ2aXJicjAiCiAgICB9LAogICAgIkRvY2tlciI6IHsKICAgICAgICAiY29udGFpbmVycyI6IFtdCiAgICB9LAogICAgIkR5bmFtaXBzIjogewogICAgICAgICJhbGxvY2F0ZV9hdXhfY29uc29sZV9wb3J0cyI6IGZhbHNlLAogICAgICAgICJkeW5hbWlwc19wYXRoIjogIiIsCiAgICAgICAgImdob3N0X2lvc19zdXBwb3J0IjogdHJ1ZSwKICAgICAgICAibW1hcF9zdXBwb3J0IjogdHJ1ZSwKICAgICAgICAic3BhcnNlX21lbW9yeV9zdXBwb3J0IjogdHJ1ZQogICAgfSwKICAgICJHcmFwaGljc1ZpZXciOiB7CiAgICAgICAgImRlZmF1bHRfbGFiZWxfY29sb3IiOiAiIzAwMDAwMCIsCiAgICAgICAgImRlZmF1bHRfbGFiZWxfZm9udCI6ICJUeXBlV3JpdGVyLDEwLC0xLDUsNzUsMCwwLDAsMCwwIiwKICAgICAgICAiZGVmYXVsdF9ub3RlX2NvbG9yIjogIiMwMDAwMDAiLAogICAgICAgICJkZWZhdWx0X25vdGVfZm9udCI6ICJUeXBlV3JpdGVyLDEwLC0xLDUsNzUsMCwwLDAsMCwwIiwKICAgICAgICAiZHJhd19saW5rX3N0YXR1c19wb2ludHMiOiB0cnVlLAogICAgICAgICJkcmF3X3JlY3RhbmdsZV9zZWxlY3RlZF9pdGVtIjogZmFsc2UsCiAgICAgICAgImRyYXdpbmdfZ3JpZF9zaXplIjogMjUsCiAgICAgICAgImdyaWRfc2l6ZSI6IDc1LAogICAgICAgICJsaW1pdF9zaXplX25vZGVfc3ltYm9scyI6IHRydWUsCiAgICAgICAgInNjZW5lX2hlaWdodCI6IDEwMDAsCiAgICAgICAgInNjZW5lX3dpZHRoIjogMjAwMCwKICAgICAgICAic2hvd19ncmlkIjogZmFsc2UsCiAgICAgICAgInNob3dfZ3JpZF9vbl9uZXdfcHJvamVjdCI6IGZhbHNlLAogICAgICAgICJzaG93X2ludGVyZmFjZV9sYWJlbHMiOiBmYWxzZSwKICAgICAgICAic2hvd19pbnRlcmZhY2VfbGFiZWxzX29uX25ld19wcm9qZWN0IjogZmFsc2UsCiAgICAgICAgInNob3dfbGF5ZXJzIjogZmFsc2UsCiAgICAgICAgInNuYXBfdG9fZ3JpZCI6IGZhbHNlLAogICAgICAgICJzbmFwX3RvX2dyaWRfb25fbmV3X3Byb2plY3QiOiBmYWxzZSwKICAgICAgICAiem9vbSI6IG51bGwKICAgIH0sCiAgICAiSU9VIjogewogICAgICAgICJpb3VyY19jb250ZW50IjogIiIsCiAgICAgICAgImxpY2Vuc2VfY2hlY2siOiB0cnVlCiAgICB9LAogICAgIk1haW5XaW5kb3ciOiB7CiAgICAgICAgImNoZWNrX2Zvcl91cGRhdGUiOiB0cnVlLAogICAgICAgICJkZWJ1Z19sZXZlbCI6IDAsCiAgICAgICAgImRlbGF5X2NvbnNvbGVfYWxsIjogNTAwLAogICAgICAgICJkaXJlY3RfZmlsZV91cGxvYWQiOiBmYWxzZSwKICAgICAgICAiZXhwZXJpbWVudGFsX2ZlYXR1cmVzIjogZmFsc2UsCiAgICAgICAgImdlb21ldHJ5IjogIkFkblF5d0FEQUFBQUFBQUFBQUFBR3dBQUIzOEFBQVEzQUFBQUFBQUFBRE1BQUFkL0FBQUVOd0FBQUFBQ0FBQUFCNEFBQUFBQUFBQUFNd0FBQjM4QUFBUTMiLAogICAgICAgICJoZHBpIjogZmFsc2UsCiAgICAgICAgImhpZGVfZ2V0dGluZ19zdGFydGVkX2RpYWxvZyI6IGZhbHNlLAogICAgICAgICJoaWRlX25ld190ZW1wbGF0ZV9idXR0b24iOiBmYWxzZSwKICAgICAgICAiaGlkZV9zZXR1cF93aXphcmQiOiB0cnVlLAogICAgICAgICJsYXN0X2NoZWNrX2Zvcl91cGRhdGUiOiAxNjM5MTIyMTUzLAogICAgICAgICJtdWx0aV9wcm9maWxlcyI6IGZhbHNlLAogICAgICAgICJvdmVybGF5X25vdGlmaWNhdGlvbnMiOiB0cnVlLAogICAgICAgICJyZWNlbnRfZmlsZXMiOiBbXSwKICAgICAgICAicmVjZW50X3Byb2plY3RzIjogW10sCiAgICAgICAgInNlbmRfc3RhdHMiOiB0cnVlLAogICAgICAgICJzcGljZV9jb25zb2xlX2NvbW1hbmQiOiAicmVtb3RlLXZpZXdlciBzcGljZTovLyVoOiVwIiwKICAgICAgICAic3RhdGUiOiAiQUFBQS93QUFBQUQ5QUFBQUF3QUFBQUFBQUFBQUFBQUFBUHdDQUFBQUFmc0FBQUFpQUhVQWFRQk9BRzhBWkFCbEFITUFSQUJ2QUdNQWF3QlhBR2tBWkFCbkFHVUFkQUFBQUFBQS8vLy8vd0FBQUlvQS8vLy9BQUFBQVFBQUFRQUFBQUxSL0FJQUFBQUMrd0FBQURZQWRRQnBBRlFBYndCd0FHOEFiQUJ2QUdjQWVRQlRBSFVBYlFCdEFHRUFjZ0I1QUVRQWJ3QmpBR3NBVndCcEFHUUFad0JsQUhRQkFBQUFQZ0FBQVdZQUFBQlpBUC8vLy9zQUFBQTBBSFVBYVFCREFHOEFiUUJ3QUhVQWRBQmxBRk1BZFFCdEFHMEFZUUJ5QUhrQVJBQnZBR01BYXdCWEFHa0FaQUJuQUdVQWRBRUFBQUdxQUFBQlpRQUFBRmtBLy8vL0FBQUFBd0FBQjBRQUFBRFQvQUVBQUFBQit3QUFBQ1lBZFFCcEFFTUFid0J1QUhNQWJ3QnNBR1VBUkFCdkFHTUFhd0JYQUdrQVpBQm5BR1VBZEFFQUFBQThBQUFIUkFBQUFFWUFCLy8vQUFBR1BnQUFBdEVBQUFBRUFBQUFCQUFBQUFnQUFBQUkvQUFBQUFJQUFBQUFBQUFBQVFBQUFDSUFkUUJwQUVJQWNnQnZBSGNBY3dCbEFISUFjd0JVQUc4QWJ3QnNBRUlBWVFCeUF3QUFBQUQvLy8vL0FBQUFBQUFBQUFBQUFBQUNBQUFBQXdBQUFDQUFkUUJwQUVjQVpRQnVBR1VBY2dCaEFHd0FWQUJ2QUc4QWJBQkNBR0VBY2dFQUFBQUEvLy8vL3dBQUFBQUFBQUFBQUFBQUlBQjFBR2tBUXdCdkFHNEFkQUJ5QUc4QWJBQlVBRzhBYndCc0FFSUFZUUJ5QVFBQUFGNy8vLy8vQUFBQUFBQUFBQUFBQUFBbUFIVUFhUUJCQUc0QWJnQnZBSFFBWVFCMEFHa0Fid0J1QUZRQWJ3QnZBR3dBUWdCaEFISUJBQUFCa1AvLy8vOEFBQUFBQUFBQUFBPT0iLAogICAgICAgICJzdGF0c192aXNpdG9yX2lkIjogIjI2ZjllNjM0LWZmMDktNDQ1My1hY2UxLTI3NzQ0ZjkzZDg1NyIsCiAgICAgICAgInN0eWxlIjogIkNoYXJjb2FsIiwKICAgICAgICAic3ltYm9sX3RoZW1lIjogIkNsYXNzaWMiLAogICAgICAgICJ0ZWxuZXRfY29uc29sZV9jb21tYW5kIjogImdub21lLXRlcm1pbmFsIC10IFwiJWRcIiAtZSBcInRlbG5ldCAlaCAlcFwiIiwKICAgICAgICAidm5jX2NvbnNvbGVfY29tbWFuZCI6ICJ2bmN2aWV3ZXIgJWg6JXAiCiAgICB9LAogICAgIk5vZGVzVmlldyI6IHsKICAgICAgICAibm9kZXNfdmlld19maWx0ZXIiOiAwCiAgICB9LAogICAgIlBhY2tldENhcHR1cmUiOiB7CiAgICAgICAgImNvbW1hbmRfYXV0b19zdGFydCI6IHRydWUsCiAgICAgICAgInBhY2tldF9jYXB0dXJlX2FuYWx5emVyX2NvbW1hbmQiOiAiIiwKICAgICAgICAicGFja2V0X2NhcHR1cmVfcmVhZGVyX2NvbW1hbmQiOiAidGFpbCAtZiAtYyArMGIgJWMgfCB3aXJlc2hhcmsgLW8gXCJndWkud2luZG93X3RpdGxlOiVkXCIgLWsgLWkgLSIKICAgIH0sCiAgICAiUWVtdSI6IHsKICAgICAgICAiZW5hYmxlX2hhcmR3YXJlX2FjY2VsZXJhdGlvbiI6IHRydWUsCiAgICAgICAgInJlcXVpcmVfaGFyZHdhcmVfYWNjZWxlcmF0aW9uIjogdHJ1ZQogICAgfSwKICAgICJWTXdhcmUiOiB7CiAgICAgICAgImJsb2NrX2hvc3RfdHJhZmZpYyI6IGZhbHNlLAogICAgICAgICJob3N0X3R5cGUiOiAid3MiLAogICAgICAgICJ2bW5ldF9lbmRfcmFuZ2UiOiAxMDAsCiAgICAgICAgInZtbmV0X3N0YXJ0X3JhbmdlIjogMiwKICAgICAgICAidm1ydW5fcGF0aCI6ICIiCiAgICB9LAogICAgIlZQQ1MiOiB7CiAgICAgICAgInZwY3NfcGF0aCI6ICIiCiAgICB9LAogICAgIlZpcnR1YWxCb3giOiB7CiAgICAgICAgInZib3htYW5hZ2VfcGF0aCI6ICIiCiAgICB9LAogICAgInR5cGUiOiAic2V0dGluZ3MiLAogICAgInZlcnNpb24iOiAiMi4yLjI3Igp9
    owner: root:root
    path: /home/ubuntu/.config/GNS3/2.2/gns3_gui.conf
    permissions: "0664"
  - encoding: b64
    content: W1VuaXRdCkRlc2NyaXB0aW9uPVRvbWNhdCA5IHNlcnZsZXQgY29udGFpbmVyCkFmdGVyPW5ldHdvcmsudGFyZ2V0CgpbU2VydmljZV0KVHlwZT1mb3JraW5nCgpVc2VyPXRvbWNhdApHcm91cD10b21jYXQKCkVudmlyb25tZW50PSJKQVZBX0hPTUU9L3Vzci9saWIvanZtL2phdmEtMTEtb3Blbmpkay1hbWQ2NCIKRW52aXJvbm1lbnQ9IkpBVkFfT1BUUz0tRGphdmEuc2VjdXJpdHkuZWdkPWZpbGU6Ly8vZGV2L3VyYW5kb20gLURqYXZhLmF3dC5oZWFkbGVzcz10cnVlIgoKRW52aXJvbm1lbnQ9IkNBVEFMSU5BX0JBU0U9L29wdC90b21jYXQvdG9tY2F0YXBwIgpFbnZpcm9ubWVudD0iQ0FUQUxJTkFfSE9NRT0vb3B0L3RvbWNhdC90b21jYXRhcHAiCkVudmlyb25tZW50PSJDQVRBTElOQV9QSUQ9L29wdC90b21jYXQvdG9tY2F0YXBwL3RlbXAvdG9tY2F0LnBpZCIKRW52aXJvbm1lbnQ9IkNBVEFMSU5BX09QVFM9LVhtczUxMk0gLVhteDEwMjRNIC1zZXJ2ZXIgLVhYOitVc2VQYXJhbGxlbEdDIgoKRXhlY1N0YXJ0PS9vcHQvdG9tY2F0L3RvbWNhdGFwcC9iaW4vc3RhcnR1cC5zaApFeGVjU3RvcD0vb3B0L3RvbWNhdC90b21jYXRhcHAvYmluL3NodXRkb3duLnNoCgpbSW5zdGFsbF0KV2FudGVkQnk9bXVsdGktdXNlci50YXJnZXQ=
    owner: root:root
    path: /etc/systemd/system/tomcat.service
    permissions: "0644"
  - encoding: b64
    content: Z3VhY2QtaG9zdG5hbWU6IGxvY2FsaG9zdApndWFjZC1wb3J0OiAgICA0ODIyCnVzZXItbWFwcGluZzogICAgL2V0Yy9ndWFjYW1vbGUvdXNlci1tYXBwaW5nLnhtbAphdXRoLXByb3ZpZGVyOiAgICBuZXQuc291cmNlZm9yZ2UuZ3VhY2Ftb2xlLm5ldC5iYXNpYy5CYXNpY0ZpbGVBdXRoZW50aWNhdGlvblByb3ZpZGVy
    owner: root:root
    path: /etc/guacamole/guacamole.properties
    permissions: "0644"
  - encoding: b64
    content: PHVzZXItbWFwcGluZz4KCiAgICA8IS0tIFBlci11c2VyIGF1dGhlbnRpY2F0aW9uIGFuZCBjb25maWcgaW5mb3JtYXRpb24gLS0+CgogICAgPCEtLSBBIHVzZXIgdXNpbmcgbWQ1IHRvIGhhc2ggdGhlIHBhc3N3b3JkIGd1YWNhZG1pbiB1c2VyIGFuZCBpdHMgbWQ1IGhhc2hlZCBwYXNzd29yZCBiZWxvdyBpcyB1c2VkIHRvIGxvZ2luIHRvIEd1YWNhbW9sZSBXZWIgVUktLT4KCiAgICA8YXV0aG9yaXplIHVzZXJuYW1lPSJtc2ktZ25zMyIgcGFzc3dvcmQ9IjU2OTJhNDhiZGU3YjMzZDk2ZmI2YjVjOTMzOGRiMmY5IiBlbmNvZGluZz0ibWQ1Ij4KICAgICAgICA8IS0tIFZOQyBjb25uZWN0aW9uIHRvIENsb3VkIEdOUzMgZGVza3RvcCAtLT4KICAgICAgICA8Y29ubmVjdGlvbiBuYW1lPSJDbG91ZCBHTlMzIj4KICAgICAgICAgICAgPHByb3RvY29sPnZuYzwvcHJvdG9jb2w+CiAgICAgICAgICAgIDxwYXJhbSBuYW1lPSJob3N0bmFtZSI+bG9jYWxob3N0PC9wYXJhbT4KICAgICAgICAgICAgPHBhcmFtIG5hbWU9InBvcnQiPjU5MDA8L3BhcmFtPgogICAgICAgICAgICA8cGFyYW0gbmFtZT0idXNlcm5hbWUiPnZhZ3JhbnQ8L3BhcmFtPgogICAgICAgICAgICA8cGFyYW0gbmFtZT0icGFzc3dvcmQiPm1zaS1nbnMzPC9wYXJhbT4KICAgICAgICA8L2Nvbm5lY3Rpb24+CiAgICA8L2F1dGhvcml6ZT4KCjwvdXNlci1tYXBwaW5nPg==
    owner: root:root
    path: /etc/guacamole/user-mapping.xml
    permissions: "0644"
  - encoding: b64
    content: IyBEZXNjcmlwdGlvbjogQ3VzdG9tIFNlcnZpY2UgVW5pdCBmaWxlCiMgRmlsZTogL2V0Yy9zeXN0ZW1kL3N5c3RlbS94MTF2bmMuc2VydmljZQpbVW5pdF0KRGVzY3JpcHRpb249IngxMXZuYyIKUmVxdWlyZXM9ZGlzcGxheS1tYW5hZ2VyLnNlcnZpY2UKQWZ0ZXI9ZGlzcGxheS1tYW5hZ2VyLnNlcnZpY2UKCltTZXJ2aWNlXQpFeGVjU3RhcnQ9L3Vzci9iaW4veDExdm5jIC1nZW9tZXRyeSAxOTIweDEwODAgLWxvb3AgLW5vcHcgLXhrYiAtcmVwZWF0IC1ub3hyZWNvcmQgLW5veGZpeGVzIC1ub3hkYW1hZ2UgLWZvcmV2ZXIgLXJmYnBvcnQgNTkwMCAtZGlzcGxheSA6MCAtYXV0aCBndWVzcwpFeGVjU3RvcD0vdXNyL2Jpbi9raWxsYWxsIHgxMXZuYwpSZXN0YXJ0PW9uLWZhaWx1cmUKUmVzdGFydFNlYz0yCgpbSW5zdGFsbF0KV2FudGVkQnk9bXVsdGktdXNlci50YXJnZXQ=
    owner: root:root
    path: /etc/systemd/system/x11vnc.service
    permissions: "0644"
  - encoding: b64
    content: U2VjdGlvbiAiRGV2aWNlIgogICAgSWRlbnRpZmllciAgIkNvbmZpZ3VyZWQgVmlkZW8gRGV2aWNlIgogICAgRHJpdmVyICAgICAgImR1bW15IgogICAgVmlkZW9SYW0gICAgMjU2MDAwCkVuZFNlY3Rpb24KClNlY3Rpb24gIk1vbml0b3IiCiAgICBJZGVudGlmaWVyICAiQ29uZmlndXJlZCBNb25pdG9yIgogICAgSG9yaXpTeW5jIDUuMCAtIDEwMDAuMAogICAgVmVydFJlZnJlc2ggNS4wIC0gMjAwLjAKICAgIE1vZGVsaW5lICIxOTIweDEwODBfNjAuMDAiIDE3Mi44MCAxOTIwIDIwNDAgMjI0OCAyNTc2IDEwODAgMTA4MSAxMDg0IDExMTggLUhTeW5jICtWc3luYwpFbmRTZWN0aW9uCgpTZWN0aW9uICJTY3JlZW4iCiAgICBJZGVudGlmaWVyICAiRGVmYXVsdCBTY3JlZW4iCiAgICBNb25pdG9yICAgICAiQ29uZmlndXJlZCBNb25pdG9yIgogICAgRGV2aWNlICAgICAgIkNvbmZpZ3VyZWQgVmlkZW8gRGV2aWNlIgogICAgRGVmYXVsdERlcHRoIDI0CiAgICBTdWJTZWN0aW9uICJEaXNwbGF5IgogICAgICAgIERlcHRoIDI0CiAgICAgICAgTW9kZXMgIjE5MjB4MTA4MF82MC4wMCIKICAgIEVuZFN1YlNlY3Rpb24KRW5kU2VjdGlvbg==
    owner: root:root
    path: /etc/X11/xorg.conf
    permissions: "0644"

runcmd:
# xfce4.sh
- export DEBIAN_FRONTEND=noninteractive
- add-apt-repository ppa:gns3/ppa -y
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
- add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- apt-get update
- apt-get upgrade -y
- apt-get install -y xfce4 lightdm firefox
- echo "/usr/sbin/lightdm" > /etc/X11/default-display-manager
- DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure lightdm
- echo set shared/default-x-display-manager lightdm | debconf-communicate
- apt-get purge -y gdm3 ubuntu-session xwayland
- apt-get autoremove -y
- rm /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf
- echo "wireshark-common wireshark-common/install-setuid boolean true" | debconf-set-selections
- apt-get install -y gns3-gui gns3-server
- apt-get install -y apt-transport-https ca-certificates curl software-properties-common
- apt-get install -y docker-ce
- usermod -aG ubridge ubuntu
- usermod -aG libvirt ubuntu
- usermod -aG kvm ubuntu
- usermod -aG wireshark ubuntu
- usermod -aG docker ubuntu
- mkdir -p /home/ubuntu/.config/GNS3/2.2
- chown ubuntu:ubuntu -R /home/ubuntu/.config/GNS3
# guacamole.sh
- GUACAMOLE_SERVER_VERSION=1.3.0
- GUACAMOLE_SERVER_URL=https://apache.org/dyn/closer.lua/guacamole/1.3.0/source/guacamole-server-1.3.0.tar.gz?action=download
- GUACAMOLE_CLIENT_VERSION=1.3.0
- GUACAMOLE_CLIENT_URL=https://apache.org/dyn/closer.lua/guacamole/1.3.0/binary/guacamole-1.3.0.war?action=download
- TOMCAT_VERSION=9.0.56
- TOMCAT_URL=https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.56/bin/apache-tomcat-9.0.56.tar.gz
- apt-get install -y libcairo2-dev libjpeg-turbo8-dev libpng-dev libtool-bin libossp-uuid-dev make
- apt-get install -y libvncserver-dev
- apt-get install -y libssl-dev
- apt-get install -y libwebp-dev
- wget -O guacamole-server-$GUACAMOLE_SERVER_VERSION.tar.gz $GUACAMOLE_SERVER_URL
- tar -xzf guacamole-server-$GUACAMOLE_SERVER_VERSION.tar.gz
- cd guacamole-server-$GUACAMOLE_SERVER_VERSION/
- ./configure --with-init-dir=/etc/init.d
- make
- make install
- ldconfig
- systemctl daemon-reload
- systemctl start guacd
- systemctl enable guacd
- cd ~
- apt-get install -y openjdk-11-jdk
- useradd -m -U -d /opt/tomcat -s /bin/false tomcat
- wget $TOMCAT_URL
- mkdir /opt/tomcat
- tar -xzf apache-tomcat-$TOMCAT_VERSION.tar.gz -C /opt/tomcat
- mv /opt/tomcat/apache-tomcat-$TOMCAT_VERSION /opt/tomcat/tomcatapp
- "chown -R tomcat: /opt/tomcat"
- chmod +x /opt/tomcat/tomcatapp/bin/*.sh
- systemctl daemon-reload
- systemctl enable --now tomcat
- ufw allow 8080/tcp
- mkdir /etc/guacamole
- wget -O /etc/guacamole-$GUACAMOLE_CLIENT_VERSION.war $GUACAMOLE_CLIENT_URL
- mv /etc/guacamole-$GUACAMOLE_CLIENT_VERSION.war /etc/guacamole/guacamole.war
- ln -s /etc/guacamole/guacamole.war /opt/tomcat/tomcatapp/webapps
- echo "GUACAMOLE_HOME=/etc/guacamole" | tee -a /etc/default/tomcat
- ln -s /etc/guacamole /opt/tomcat/tomcatapp/.guacamole
- systemctl restart tomcat guacd
- ufw allow 4822/tcp
# x11vnc.sh
- apt-get install -y x11vnc xserver-xorg-video-dummy
- x11vnc -storepasswd msi-gns3 /etc/x11vnc.pass
- systemctl daemon-reload
- systemctl enable x11vnc.service
- chown ubuntu:ubuntu -R /home/ubuntu

power_state:
  mode: reboot
  message: Rebooting...