# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    # Konfiguracija za GNS3 client
    config.vm.define :client do |client|
        client.vm.provider "virtualbox" do |v|
            v.name = "cloud-gns3"
            v.cpus = 2
            v.memory = 2048
            v.gui = true
        end
        client.vm.hostname = "cloud-gns3"
        client.vm.network "private_network", ip: "192.168.221.101"
        #client.vm.provision :shell, path: "gns3-server.sh"
        #client.vm.provision :shell, path: "gns3-client.sh"
        client.vm.provision :shell, path: "provision.sh"
    end
end