# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    # Konfiguracija za GNS3 client
    config.vm.define :client do |client|
        client.vm.provider "virtualbox" do |v|
            v.name = "gns3-client"
            v.cpus = 1
            v.memory = 1024
            v.gui = true
            v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
        end
        client.vm.hostname = "gns3-client"
        client.vm.network "private_network", ip: "192.168.221.101"
        client.vm.provision :shell, path: "gns3-server.sh"
        client.vm.provision :shell, path: "gns3-client.sh"
    end
end